# Generated by Django 3.2.9 on 2021-11-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('eMail', models.CharField(max_length=200)),
                ('passWord', models.CharField(max_length=200)),
            ],
        ),
    ]
