# Generated by Django 3.2.9 on 2022-04-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxlApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=80)),
                ('phone', models.BigIntegerField(max_length=11)),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('street_add', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
