# Generated by Django 3.2.9 on 2022-04-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxlApp', '0002_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
