# Generated by Django 3.2.9 on 2022-04-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxlApp', '0003_alter_customers_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.BigIntegerField()),
                ('prod_name', models.CharField(max_length=200)),
                ('prod_price', models.BigIntegerField()),
                ('prod_img', models.URLField()),
                ('stock_qty', models.BigIntegerField()),
            ],
        ),
    ]
